# docker-compose.yml
version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html   #Sciezka do plikow html i hls
    ports:
      - "8080:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    volumes:
      - /home/mikolajczykk/.cloudflared:/etc/cloudflared #sciezka do folderu z tunelem  
    command: tunnel --config /etc/cloudflared/config.yml run #sciezka do konfiguracji cloudflare
    user: root
    restart: unless-stopped
